### ISSUE TITLE
スマホでカメラ撮影時にアスペクト比がおかしい。

### ISSUE THREAD

**Issue by seidaiegoshi** [seidaiegoshi/js-chanpionship#47]

**Comment by seidaiegoshi** [comment]
縦長の映像を横長に伸ばしてしまっているのかも

**Comment by seidaiegoshi** [comment]
css側もアスペクト維持設定が必要

**Comment by at-voice** [comment]
[https://adiary.adiary.jp/0420](https://adiary.adiary.jp/0420)

_mediaDevices.getUserMediaの説明を隅々まで読むと書いてあるのですが、widthとheightの指定は要望であって強制ではありません。

ピッタリとマッチする解像度がカメラ（ビデオソース）に存在しない場合、ブラウザはそれに近い画像サイズを設定します。スマホにおいては、そのサイズが 900x1600 なのです……。

ブラウザにおいて縦画面・横画面という区別はありません。ブラウザの media stream は状況（縦横）に応じてサイズが変化することを想定していないわけです。ですので、スマホのブラウザは縦横設定を無視して近い画像サイズを選定します。_

**Comment by seidaiegoshi** [comment]
今はvideoの画像をcanvasへ描画するようになっている。
videoのサイズは0で指定。canvasも指定なし。
canvasのデフォルトサイズが300*150なので、それで描画されてるぽい。
それをCSSで引き伸ばしている。

**Comment by seidaiegoshi** [comment]
PCのアスペクト比は良くなったが、改善しなかった

**Comment by seidaiegoshi** [comment]
沼

**Comment by seidaiegoshi** [comment]
https://adiary.adiary.jp/0420

**Comment by seidaiegoshi** [comment]
スマホかわらず
